### ISSUE TITLE
Update Extension in Zed's Extensions Repo

### ISSUE THREAD

**Issue by Z7-Z7L** [clseibold/zed-odin#5]
error message:
Language server error: 
```c
ols

no asset found matching "ols-x86_64-windows-msvc.zip"
-- stderr--
```

**Comment by clseibold** [comment]
Hello, thanks for reporting this bug. The extension has zed try to download the language server for odin (ols), but looks like it's either not downloading the asset, or the asset's name in the code is incorrect. I will look into this, thanks.

**Comment by clseibold** [comment]
Ah, this was already fixed by #3 , zed's extension repo just hasn't had this extension updated yet. I will close this when that gets done. Thanks again for reporting.

**Comment by Z7-Z7L** [comment]
> Ah, this was already fixed by #3 , zed's extension repo just hasn't had this extension updated yet. I will close this when that gets done. Thanks again for reporting.

can I install it as a dev extension, when I download the `zed-odin-main` folder and try to install it as dev extension nothing happen

**Comment by clseibold** [comment]
Not sure why it's not working as a dev extension, but I'll try to do a PR to update the extension today.

**Comment by clseibold** [comment]
I have opened a PR to update the extension in zed's extensions repo: https://github.com/zed-industries/extensions/pull/1474

**Comment by Z7-Z7L** [comment]
thanks 🙏

**Comment by clseibold** [comment]
The first issue is mentioned in #4 and has not been fixed yet.
As for the second issue, Odin's formatter automatically removes semicolons at the end of statements because semicolons are optional in Odin. There might be a way to change this, but you'll have to look at the ols and odinfmt documentation here: https://github.com/DanielGavin/ols

**Comment by clseibold** [comment]
Closing issue now that v0.1.1 has been merged: https://github.com/zed-industries/extensions/pull/1474#event-14476130798
